[package]
name = "matryoshka-sqlite"
version = "0.1.0"
authors = ["Christopher Gundler <christopher@gundler.de>"]
edition = "2018"

[dependencies]
regex = "1"
const_format = "0.2"

[dependencies.rusqlite]
version = "0.24"
features = ["bundled", "blob"]
