[package]
name = "matryoshka-sqlite"
version = "0.2.0"
authors = ["Christopher Gundler <christopher@gundler.de>"]
edition = "2018"

[dependencies]
regex = "1"
const_format = "0.2"

[dependencies.rusqlite]
version = "0.24"
features = ["bundled", "blob", "limits"]

[dev-dependencies]
test-case = "1.1"